name: Conditional Workflow-2

on:
  push:
    branches:
      - main

jobs:
  job_a:
    runs-on: ubuntu-latest
    steps:
      - name: Step A
        run: echo "Step A executed successfully"

  job_b:
    runs-on: ubuntu-latest
    needs: job_a
    if: ${{ needs.job_a.outcome == 'success' }}
    steps:
      - name: Step B
        run: echo "Step B executed because Step A succeeded"
