name: Conditional Steps based on Runner

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     
      - name: Run Ubuntu-specific task (replace with your command)
        if: runner == 'ubuntu-latest'  
        run: echo "This step runs only on Ubuntu runners"

      
      - name: Run self-hosted specific task (replace with your command)
        if: runner == 'self-hosted'  
        run: echo "This step runs only on self-hosted runners"
