name: Environment example
on:
  # push: 
  #     branches: 
  #         - main
  workflow_dispatch:
env:
  continent: "${{vars.CONTINENT}}"
jobs:
  Environment-Test:
    env: 
      country: India
    runs-on: ubuntu-latest
    steps:
      - name: specific to step
        env: 
          city: Delhi 
        run : 
            echo "${{env.city}} is a city located in the northern part of ${{env.country}}, which is situated on the ${{env.continent}} continent"
            
      - name: specific to step
        run : echo "Hello Im from $city, which is part of $country"
      
      - name: Defaults
        run : echo "Hello My run Id is ${{github.run_id}} which inside Reep ${{github.repository}}"
